/**
 * Institutional Negotiation Memory & Intelligence Console
 * Domain Model & Core Type Definitions
 */

export type SupplyBalance = 'SHORTAGE' | 'BALANCED' | 'SURPLUS';
export type LeverageLevel = 'HIGH' | 'MEDIUM' | 'LOW';
export type UrgencyLevel = 'URGENT' | 'NORMAL' | 'FLEXIBLE';
export type DecisionStatus = 'PENDING' | 'ACCEPTED' | 'MODIFIED' | 'OVERRIDDEN' | 'REJECTED';
export type SeverityLevel = 'CRITICAL' | 'MODERATE' | 'NEUTRAL' | 'FAVORABLE';

/**
 * 1. NegotiationCase
 * Active negotiation episode requiring tactical analysis & decision support.
 */
export interface NegotiationCase {
  id: string;
  counterparty: string;
  product: string;
  contractValue: number | string;
  targetQuantity: number | string;
  targetLeadTime: string;
  marketTrend: string;
  paymentTerms: string;
  supplyBalance: SupplyBalance;
  supplierLeverage: LeverageLevel;
  buyerLeverage: LeverageLevel;
  urgency: UrgencyLevel;
  alternatives: number;
  category?: string;
  negotiationObjective?: string;
  constraints?: string;
  createdAt?: string;
  updatedAt?: string;
}

/**
 * Condition Vector used for multi-dimensional similarity retrieval
 */
export interface ConditionVector {
  supply_balance: SupplyBalance;
  supplier_leverage: LeverageLevel;
  buyer_leverage: LeverageLevel;
  urgency: UrgencyLevel;
  alternatives: number;
}

/**
 * 2. HistoricalMemory
 * Institutional precedent preserved in Hindsight memory bank.
 */
export interface HistoricalMemory {
  id: string;
  organization: string;
  category: string;
  date: string;
  strategy: string;
  conditions: {
    supplyBalance: SupplyBalance | string;
    supplierLeverage: LeverageLevel | string;
    buyerLeverage: LeverageLevel | string;
    alternatives?: number;
    marketTrend?: string;
    narrative?: string;
  };
  outcome: string;
  relevanceScore: number;
  result: 'SUCCESS' | 'PARTIAL' | 'FAILED' | string;
  lessons: string;
  tacticsAttempted?: string[];
  whatWorked?: string[];
  whatFailed?: string[];
  tradeoffs?: string;
}

/**
 * 3. ConditionDifference
 * Dimensional delta comparing past precedents against active case conditions.
 */
export interface ConditionDifference {
  dimension: string;
  historicalValue: string | number;
  currentValue: string | number;
  impact: string;
  severity: SeverityLevel;
}

export interface ConditionDiffAnalysis {
  caseId: string;
  comparedMemoryId: string;
  differences: ConditionDifference[];
  summary: string;
  hasMeaningfulShift: boolean;
  repeatHistoricalPlaybookSafe: boolean;
}

/**
 * 4. Reflection
 * Multi-memory synthesis detecting aligned patterns and conflicting precedents.
 */
export interface ReflectionEvidenceItem {
  memoryId: string;
  fact: string;
  relevance?: number;
  context?: string;
}

export interface Reflection {
  memoriesConsidered: string[];
  alignedPatterns: string[];
  conflictingPrecedents: string[];
  synthesis: string;
  evidence: ReflectionEvidenceItem[];
  reflectionSource?: 'hindsight_reflect_llm' | 'fallback_rule_based';
}

/**
 * 5. RecommendedStrategy
 * Strategy generated by Hindsight reflection grounded in historical memory.
 */
export interface RecommendedStrategy {
  title: string;
  confidence: number;
  rationale: string;
  tacticalLevers: string[];
  supportingMemories: string[];
  risks: string[];
  tacticsToAvoid?: string[];
  concessionStrategy?: string;
}

/**
 * 6. HumanDecision
 * Human Procurement Manager's final discretionary decision.
 */
export interface HumanDecision {
  id?: string;
  caseId: string;
  status: DecisionStatus;
  selectedStrategy: string;
  modifications: string;
  notes: string;
  timestamp: string;
  decidedBy?: string;
}

/**
 * 7. RetainedOutcome
 * Post-negotiation outcome retained back into Hindsight memory bank.
 */
export interface RetainedOutcome {
  id?: string;
  caseId: string;
  decision: HumanDecision | string;
  actualOutcome: string;
  lessons: string;
  retainedStrategy: string;
  timestamp: string;
  financialImpact?: string;
  termsAchieved?: string;
  counterparty?: string;
  category?: string;
}

/**
 * API Request & Response Contracts
 */
export interface MemoryRecallRequest {
  case_id?: string;
  query?: string;
  condition_vector: ConditionVector;
  top_k?: number;
  category?: string;
}

export interface MemoryRecallResponse {
  memories: HistoricalMemory[];
  retrieval_metadata: {
    method: 'hindsight_vector_hybrid' | 'vector_similarity' | 'mock_precedent';
    top_k: number;
    bank_id: string;
    total_evaluated?: number;
  };
}

export interface ConditionDiffRequest {
  current_case: NegotiationCase;
  reference_memory_id?: string;
}

export interface ConditionDiffResponse {
  case_id: string;
  reference_memory_id: string;
  differences: ConditionDifference[];
  summary: string;
  has_meaningful_shift: boolean;
  repeat_warning?: string;
  recommended_pivot?: string;
}

export interface ReflectRequest {
  case_id: string;
  memories_to_consider?: string[];
  condition_diff?: ConditionDiffAnalysis;
}

export interface ReflectResponse {
  case_id: string;
  reflection: Reflection;
}

export interface StrategyRecommendRequest {
  case_id: string;
  reflection?: Reflection;
  condition_diff?: ConditionDiffAnalysis;
}

export interface StrategyRecommendResponse {
  case_id: string;
  strategy: RecommendedStrategy;
  reflection_source: 'hindsight_reflect_llm' | 'fallback_rule_based';
}

export interface DecisionRecordRequest {
  case_id: string;
  status: DecisionStatus;
  selected_strategy: string;
  modifications?: string;
  notes?: string;
  decided_by?: string;
}

export interface DecisionRecordResponse {
  decision_id: string;
  case_id: string;
  recorded_at: string;
  status: DecisionStatus;
  message: string;
}

export interface OutcomeRetainRequest {
  case_id: string;
  actual_outcome: string;
  lessons: string;
  retained_strategy: string;
  financial_impact?: string;
  terms_achieved?: string;
  decision_id?: string;
}

export interface OutcomeRetainResponse {
  retained_outcome_id: string;
  memory_id: string;
  case_id: string;
  hindsight_synced: boolean;
  retained_at: string;
  message: string;
}

export interface MemoryCluster {
  id: string;
  theme: string;
  category: string;
  memoryCount: number;
  representativeDeal: string;
  dominantCondition: string;
  commonTactics: string[];
}

export interface MemoryTimelineEvent {
  id: string;
  date: string;
  counterparty: string;
  category: string;
  event: string;
  conditionShift: string;
  outcome: string;
}
